[phases.setup]
nixPkgs = ['nodejs_20', 'pnpm']

[phases.install]
cmds = ['cd backend && pnpm install --frozen-lockfile']

[phases.build]
cmds = ['cd backend && pnpm run build']

[start]
cmd = 'cd backend && pnpm start:prod'